#Tugas 2


Carilah data yang bertipe numerik ( data klassifikasi)

1. Lakukan proses diskritisasi dengan equal width dan equal frequency

2. Lakukan proses diskritisasi  dengan basis entropy

yang diupload adalah link github ( web statis dari jupyter book)

In [2]:
import pandas as pd

In [4]:
dataset_url = "https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv"
df = pd.read_csv(dataset_url)
df.head(10)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

1. Lakukan proses diskritisasi dengan equal width dan equal frequency

In [5]:
SEPAL_LENGTH_SERIES = df["sepal.length"]
SEPAL_WIDTH_SERIES = df["sepal.width"]
PETAL_LENGTH_SERIES = df["petal.length"]
PETAL_WIDTH_SERIES = df["petal.width"]

**Equal Width**

Sepal Length

In [6]:
# Interval Equal-width

labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

sepal_length_ew_binning = pd.cut(SEPAL_LENGTH_SERIES, amount_of_binning, True, labels)
labelled_sepal_length_ew_binning = sepal_length_ew_binning.value_counts()
interval_sepal_length_ew_binning = pd.cut(SEPAL_LENGTH_SERIES, amount_of_binning, True).value_counts()


# Dataframe dari Sepal-width dan Sepal Category
df_sepal_length_ew = pd.DataFrame(pd.concat((SEPAL_LENGTH_SERIES, sepal_length_ew_binning), axis=1))


# Ubah nama colom
df_sepal_length_ew.columns = ["sepal_length", "category"]
df_sepal_length_ew

     sepal_length       category
0             5.1  sedikit_lebar
1             4.9  sedikit_lebar
2             4.7  sedikit_lebar
3             4.6  sedikit_lebar
4             5.0  sedikit_lebar
..            ...            ...
145           6.7          lebar
146           6.3          lebar
147           6.5          lebar
148           6.2          lebar
149           5.9          lebar

[150 rows x 2 columns]

Sepal Width

In [7]:
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

sepal_width_ew_binning = pd.cut(SEPAL_WIDTH_SERIES, amount_of_binning, True, labels)
labelled_sepal_width_ew_binning = sepal_width_ew_binning.value_counts()
interval_sepal_width_ew_binning = pd.cut(SEPAL_WIDTH_SERIES, amount_of_binning, True).value_counts()

# Dataframe dari sepal-width dan sepal category
df_sepal_width_ew = pd.DataFrame(pd.concat((SEPAL_WIDTH_SERIES, sepal_width_ew_binning), axis=1))

# Mengubah nama colom
df_sepal_width_ew.columns = ["sepal.width", "category"]

df_sepal_width_ew

     sepal.width       category
0            3.5          lebar
1            3.0          lebar
2            3.2          lebar
3            3.1          lebar
4            3.6          lebar
..           ...            ...
145          3.0          lebar
146          2.5  sedikit_lebar
147          3.0          lebar
148          3.4          lebar
149          3.0          lebar

[150 rows x 2 columns]

Petal Lenght

In [8]:
# intervals Equal-width
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

petal_length_ew_binning = pd.cut(PETAL_LENGTH_SERIES, amount_of_binning, True, labels)
labelled_petal_length_ew_binning = petal_length_ew_binning.value_counts()
interval_petal_length_ew_binning = pd.cut(PETAL_LENGTH_SERIES, amount_of_binning, True).value_counts()

# Dataframe dari petal-width dan petal category
df_petal_length_ew =  pd.DataFrame(pd.concat((PETAL_LENGTH_SERIES,petal_length_ew_binning), axis=1))

# Mengubah nama colom
df_petal_length_ew.columns = ["petal_length", "category"]

df_petal_length_ew

     petal_length       category
0             1.4  sedikit_lebar
1             1.4  sedikit_lebar
2             1.3  sedikit_lebar
3             1.5  sedikit_lebar
4             1.4  sedikit_lebar
..            ...            ...
145           5.2   sangat_lebar
146           5.0   sangat_lebar
147           5.2   sangat_lebar
148           5.4   sangat_lebar
149           5.1   sangat_lebar

[150 rows x 2 columns]

Petal Widht

In [9]:
#  Interval Equal-width
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

petal_width_ew_binning = pd.cut(PETAL_WIDTH_SERIES, amount_of_binning, True, labels)
labelled_petal_width_ew_binning = petal_width_ew_binning.value_counts()
interval_petal_width_ew_binning = pd.cut(PETAL_WIDTH_SERIES, amount_of_binning, True).value_counts()

# Dataframe dari petal-width dan petal category
df_petal_width = pd.DataFrame(pd.concat((PETAL_WIDTH_SERIES, petal_width_ew_binning), axis=1))

# Mengubah nama colom
df_petal_width.columns = ["petal.width", "category"]
df_petal_width

     petal.width       category
0            0.2  sedikit_lebar
1            0.2  sedikit_lebar
2            0.2  sedikit_lebar
3            0.2  sedikit_lebar
4            0.2  sedikit_lebar
..           ...            ...
145          2.3   sangat_lebar
146          1.9   sangat_lebar
147          2.0   sangat_lebar
148          2.3   sangat_lebar
149          1.8   sangat_lebar

[150 rows x 2 columns]

**Equal Frequency**

Sepal Length

In [10]:
# Interval Equal-frequency 

labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

sepal_length_ef_binning = pd.qcut(SEPAL_LENGTH_SERIES, amount_of_binning, labels)
labelled_sepal_length_ef_binning = sepal_length_ef_binning.value_counts()
interval_sepal_length_ef_binning = pd.qcut(SEPAL_LENGTH_SERIES, amount_of_binning).value_counts()

# Dataframe dari sepal-length dan sepal category
df_sepal_length_ef = pd.DataFrame(pd.concat((SEPAL_LENGTH_SERIES, sepal_length_ef_binning), axis=1))

# Mengubah nama kolom
df_sepal_length_ef.columns = ["sepal_length", "category"]
df_sepal_length_ef

     sepal_length       category
0             5.1  sedikit_lebar
1             4.9  sedikit_lebar
2             4.7  sedikit_lebar
3             4.6  sedikit_lebar
4             5.0  sedikit_lebar
..            ...            ...
145           6.7   sangat_lebar
146           6.3          lebar
147           6.5   sangat_lebar
148           6.2          lebar
149           5.9          lebar

[150 rows x 2 columns]

Sepal Width

In [11]:
# Intervals Equal-frequency

labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

sepal_width_ef_binning = pd.qcut(SEPAL_WIDTH_SERIES, amount_of_binning, labels)
labelled_sepal_width_ef_binning = sepal_width_ef_binning.value_counts()
interval_sepal_width_ef_binning = pd.qcut(SEPAL_WIDTH_SERIES, amount_of_binning).value_counts()

# Dataframe dari sepal-width dan sepal category
df_sepal_width_ef = pd.DataFrame(pd.concat((SEPAL_WIDTH_SERIES, sepal_width_ef_binning), axis = 1))

# Mengubah nama kolom
df_sepal_width_ef.columns = ["sepal_width", "category"]
df_sepal_width_ef

     sepal_width       category
0            3.5   sangat_lebar
1            3.0          lebar
2            3.2          lebar
3            3.1          lebar
4            3.6   sangat_lebar
..           ...            ...
145          3.0          lebar
146          2.5  sedikit_lebar
147          3.0          lebar
148          3.4   sangat_lebar
149          3.0          lebar

[150 rows x 2 columns]

Petal Length

In [12]:
# Interval equal-frequency

labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

petal_length_ef_binning = pd.qcut(PETAL_LENGTH_SERIES, amount_of_binning, labels)
labelled_petal_length_ef_binning = petal_length_ef_binning.value_counts()
interval_petal_length_ef_binning = pd.qcut(PETAL_LENGTH_SERIES, amount_of_binning).value_counts()

# Dataframe dari petal-length dan petal category
df_petal_length_ef = pd.DataFrame(pd.concat((PETAL_LENGTH_SERIES, petal_length_ef_binning), axis=1))

# Mengubah nama kolom
df_petal_length_ef.columns = ["petal_length", "category"]
df_petal_length_ef

     petal_length       category
0             1.4  sedikit_lebar
1             1.4  sedikit_lebar
2             1.3  sedikit_lebar
3             1.5  sedikit_lebar
4             1.4  sedikit_lebar
..            ...            ...
145           5.2   sangat_lebar
146           5.0   sangat_lebar
147           5.2   sangat_lebar
148           5.4   sangat_lebar
149           5.1   sangat_lebar

[150 rows x 2 columns]

Petal Width

In [13]:
# Intervals equal-frequency

labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(labels)

petal_width_ef_binning = pd.qcut(PETAL_WIDTH_SERIES, amount_of_binning, labels)
labelled_petal_width_ef_binning = petal_width_ef_binning.value_counts()
interval_petal_width_ef_binning = pd.qcut(PETAL_WIDTH_SERIES, amount_of_binning).value_counts()

# Dataframe dari petal-width dan petal category
df_petal_width_ef = pd.DataFrame(pd.concat((PETAL_WIDTH_SERIES, petal_width_ef_binning), axis = 1))

# Mengubah nama kolom
df_petal_width_ef.columns = ["petal_width", "category"]
df_petal_width_ef

     petal_width       category
0            0.2  sedikit_lebar
1            0.2  sedikit_lebar
2            0.2  sedikit_lebar
3            0.2  sedikit_lebar
4            0.2  sedikit_lebar
..           ...            ...
145          2.3   sangat_lebar
146          1.9   sangat_lebar
147          2.0   sangat_lebar
148          2.3   sangat_lebar
149          1.8   sangat_lebar

[150 rows x 2 columns]

2. Lakukan proses diskritisasi  dengan basis entropy

**Entropy**

Entropy adalah nilai informasi yang menyatakan ukuran ketidakpastian(impurity) dari attribut dari suatu kumpulan obyek data dalam satuan bit


**Rumus Entropy**

$$
\begin{align*}
\displaystyle Entropy(S) &= \sum_{i=0}^{k} -pi \ log_{2} \ pi \\
\end{align*}
$$

In [14]:
from math import log2
target_data = df_petal_width_ef
target_data

     petal_width       category
0            0.2  sedikit_lebar
1            0.2  sedikit_lebar
2            0.2  sedikit_lebar
3            0.2  sedikit_lebar
4            0.2  sedikit_lebar
..           ...            ...
145          2.3   sangat_lebar
146          1.9   sangat_lebar
147          2.0   sangat_lebar
148          2.3   sangat_lebar
149          1.8   sangat_lebar

[150 rows x 2 columns]

In [15]:
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]

In [16]:
#Fungsi menghitung banyaknya data setiap kategori ,hitung setiap nilai berdasarkan kategori yang diberikan
def countEveryCategory(data_column, labels, column, category):
    group = data_column.groupby(category).count()
    amount_of_every_category = []
    for label in labels:
        amount_of_every_category.append(group.loc[label, column])
    return amount_of_every_category

In [17]:
#Fungsi menghitung banyaknya data setiap kategori berdasarkan nilai pembagi atau split value yang diberikan
#Pisahkan data yang diberikan berdasarkan kategori dan nilai split
def split(split_value, data_column, labels, col, category):
    less_group = data_column[data_column[col] < split_value]
    greater_group = data_column[data_column[col] >= split_value]
    
    length_less_group = countEveryCategory(less_group, labels, col, category)
    length_greater_group = countEveryCategory(greater_group, labels, col, category)
    
    return (length_less_group, length_greater_group)

- Fungsi menghitung perbedaan gain antara entropi inisial dengan entropi nilai pembagi yang diberikan

**Rumus:**


$$Gain(E_{new}) = (E_{initial}) \ - (E_{new})$$

In [18]:
# menghitung perolehan informasi dari entropi awal dan entropi baru

def count_gain(inisial_entropy, new_entropy):
  return inisial_entropy - new_entropy
#Fungsi menghitung entropy

# count entropy
def count_entropy(data_target):
    all_prob = []
    for prob in data_target:
        if (prob/sum(data_target) != 0):
            all_prob.append(prob/sum(data_target) * log2(prob/sum(data_target)))
        else:
            all_prob.append(0)
    return -(sum(all_prob))

- Fungsi menghitung Info entropy berdasarkan nilai pembagi atau *split value* yang diberikan

**Rumus :**



$$ Info_A(D) = \frac{|D_1|}{|D|} Entropy (D_1)\frac{|D_2|}{|D|}+ Entropy (D_2)$$

In [19]:
# Hitung entropi pada nilai split yang diberikan
def info(d, data_target):
    temp = []
    for value in d:
        temp.append((sum(value) / data_target.shape[0]) * count_entropy(value))
    return sum(temp)

**Implementasi**

- Hitung target entropy
- Hitung target entropy dengan split value
- Hitung entropy gain

In [22]:
# Entropy data target

initial_data_target_entropy = count_entropy(countEveryCategory(target_data, labels, target_data.columns[0], target_data.columns[1]))

**A.**

In [23]:
# Hitung Entropi untuk target yang diberi nilai split, nilai split = 0,7
entropy_data_target_1 = info(split(0.7, target_data, labels, target_data.columns[0], target_data.columns[1]), target_data)

# Information gain (Entropy data target and entropy_data_target_1)
count_gain(initial_data_target_entropy, entropy_data_target_1)

0.9182958340544896

**B.**

In [24]:
# Hitung Entropi untuk target yang diberi nilai split, nilai split = 0,7
entropy_data_target_2 = info(split(1.4, target_data, labels, target_data.columns[0], target_data.columns[1]), target_data)

# Information gain (Entropy data target and entropy_data_target_2)
count_gain(initial_data_target_entropy, entropy_data_target_2)

0.6536600192724277

**C.**

In [25]:
# Hitung Entropi untuk target yang diberi nilai split, nilai split = 0,7
entropy_data_target_3 = info(split(2.1, target_data, labels, target_data.columns[0], target_data.columns[1]), target_data)

# Information gain (Entropy data target and entropy_data_target_3)
count_gain(initial_data_target_entropy, entropy_data_target_3)

0.2985203537604644